on:
  script:
    config:
      #every: "10 6 * * *"
      timeZone: Europe/Berlin
    run: |
      const result = await helpers.axios.get("https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/rki_key_data_hubv/FeatureServer/0/query?where=AdmUnitId%20%3E%3D%20-1%20AND%20AdmUnitId%20%3C%3D%200&outFields=*&outSR=4326&f=json")
      return result.data.features
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          outputs: ${{ toJson(on.script.outputs) }}
        run: |
          echo outputs: $outputs
      - name: send message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ALERTS_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_ALERTS_TOKEN }}
          #color: "#48f442"
          message:
            "**COVID-19 Zahlen** :black_circle:\n
            Anzahl Neuinfektionen: ${{ on.script.outputs.attributes.AnzFallNeu }}\n
            Anzahl Todesfälle 24h: ${{ on.script.outputs.attributes.AnzTodesfallNeu }}\n
            7 Tage Inzidenz: ${{ on.script.outputs.attributes.Inz7T }}\n"
