# origin:  MarcMogdanz /actionsflow-workflows 
on:
  rss:
    url:
      # myDealz
      - {{ secrets.MYDEALZ_RSS_URL }}
    config:
      filterOutputs:
        title: 1
        link: 1
      format: |
        // remove "
        // max length for slack is 151, use 140 to have space for an emoji
        item.title = item.title.split('"').join("").substring(0, 140);
        return item;
jobs:
  notify:
    name: Send notifications
    runs-on: ubuntu-latest
    steps:
      # Used for debugging
      - name: Print to console
        env:
          title: ${{ on.rss.outputs.title }}
          link: ${{ on.rss.outputs.link }}
        run: |
          echo title: $title
          echo link: $link
      - name: SIGNL4 Alerting
        uses: signl4/signl4-action-alert@v1
        with:
          team-secret: ${{ secrets.SIGNL4_TEAM_SECRET }}
          title: 'MyDealz Alert'
          message: title: ${{ on.rss.outputs.title }}, link: ${{ on.rss.outputs.link }}
