on:
  email:
    imap:
      host: ${{ secrets.EMAIL_HOST }}
      user: ${{secrets.EMAIL_USER}}
      password: ${{secrets.EMAIL_PASS}}
      tls: true
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          subject: ${{on.email.outputs.subject}}
          text: ${{on.email.outputs.text}}
        run: |
          echo subject: $subject
          echo text: $text
          echo done
      - name: Slack notification
        uses: Ilshidur/action-slack@2.1.0
        env:
          subject: ${{on.email.outputs.subject}}
          #body: ${{on.email.outputs.text}}
          SLACK_WEBHOOK: ${{ secrets.SLACK_NETWORK }}
          SLACK_CUSTOM_PAYLOAD: '{ "text": "Neue Nachricht auf deiner fritz.box {{ subject }} "}'
