# Slack Integration from  MarcMogdanz /actionsflow-workflows 
on:
  rss:
    url:
      #- https://news.google.com/rss?pz=1&cf=all&hl=de&gl=DE&ceid=DE:de
      - https://rp-online.de/feed.rss
      - https://www.spiegel.de/schlagzeilen/eilmeldungen/index.rss
      - https://taz.de/Themen-des-Tages/!p15;rss/
      #- http://rss.filmstarts.de/fs/news/serien
    config:
      #limit: 10
      filterOutputs:
        title: 1
        link: 1
      format: |
        item.hostname = new URL(item.link).hostname;
        item.title = item.title.split('"').join("").substring(0, 140);
        return item;
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo contentSnippet: $contentSnippet
          echo link: $link
          echo done
      #- name: SIGNL4 Alerting
       # uses: signl4/signl4-action-alert@v1
       # with:
       #   team-secret: ${{ secrets.SIGNL4_TEAM_SECRET }}
       #   title: ${{on.rss.outputs.title}}
       #   message: ${{on.rss.outputs.contentSnippet}} ${{on.rss.outputs.link}}
      - name: Slack notification
        uses: Ilshidur/action-slack@2.1.0
        env:
          title: ${{ on.rss.outputs.title }}
          link: ${{ on.rss.outputs.link }}
          hostname: ${{ on.rss.outputs.hostname }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_NEWS_BOT }}
          SLACK_CHANNEL: news
          SLACK_CUSTOM_PAYLOAD: '{ "text": "{{ title }}", "blocks": [ { "type": "header", "text": { "type": "plain_text", "text": ":mega: {{ title }}", "emoji": true } }, { "type": "section", "text": { "type": "mrkdwn", "text": "`{{ hostname }}` - <{{ link }}|Click here to open>" } }, { "type": "divider" } ] }'
