# Slack Integration from  MarcMogdanz /actionsflow-workflows 
on:
  rss:
    url:
      #- https://rp-online.de/feed.rss
      #- http://www.chip.de/rss/rss_downloads.xml
      # tttt
      - https://www.spiegel.de/schlagzeilen/eilmeldungen/index.rss
      - https://taz.de/Themen-des-Tages/!p15;rss/
    config:
      #limit: 10
      filterOutputs:
        title: 1
        link: 1
        content_tier: 1
      filter:
        content_tier:
          $not:
            locked
      format: |
        item.hostname = new URL(item.link).hostname;
        item.title = item.title.split('"').join("").substring(0, 140);
        return item;
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          #contentSnippet: ${{on.rss.outputs.contentSnippet}}
          link: ${{on.rss.outputs.link}}
          #debug
          ct: ${{ on.rss.outputs.content_tier }}
        run: |
          echo title: $title
          #echo contentSnippet: $contentSnippet
          echo link: $link
          echo Content: $ct
          echo done
      - name: Slack notification
        uses: Ilshidur/action-slack@2.1.0
        env:
          title: ${{ on.rss.outputs.title }}
          link: ${{ on.rss.outputs.link }}
          hostname: ${{ on.rss.outputs.hostname }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_NEWS_BOT }}
          SLACK_CHANNEL: news
          SLACK_CUSTOM_PAYLOAD: '{ "text": "{{ title }}", "blocks":
                                 [ { "type": "header", "text":
                                 { "type": "plain_text", "text": ":mega: {{ title }}", "emoji": true } },
                                 { "type": "section", "text": { "type": "mrkdwn", "text": "`{{ hostname }}` - <{{ link }}|Click here to open>" } },
                                 { "type": "divider" } ] }'
      - name: Test Success
        env:
          title: ${{ on.rss.outputs.title }}
          link: ${{ on.rss.outputs.link }}
          hostname: ${{ on.rss.outputs.hostname }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: Ich bin Che
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_TEST }}
