on:
  rss:
    url:
      - ${{ secrets.MYDEALZ_RSS_URL }}
      - https://news.google.com/rss?pz=1&cf=all&hl=de&gl=DE&ceid=DE:de
    config:
      limit: 5
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo contentSnippet: $contentSnippet
          echo link: $link
          echo done
      - name: SIGNL4 Alerting
        uses: signl4/signl4-action-alert@v1
        with:
          team-secret: ${{ secrets.SIGNL4_TEAM_SECRET }}
          title: 'Rainers Wetterinfo'
          message: Die aktuelle Teperatur beträgt ${{on.weather.outputs.current.temp}}°, der Tageshöchstwert wird bei ${{on.weather.outputs.daily[0].temp.day}}° liegen.
                  ${{on.weather.outputs.daily[0].weather[0].description}}
