on:
  script:
    config:
      force: true
      skipSchedule: true
      manualRunEvent:
        - workflow_dispatch
        - push
    run: |
      const result = await helpers.axios.get("https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/rki_key_data_hubv/FeatureServer/0/query?where=ObjectId%20%3E%3D%200%20AND%20ObjectId%20%3C%3D%202%20AND%20AdmUnitId%20%3E%3D%200%20AND%20AdmUnitId%20%3C%3D%201&outFields=AnzFallNeu,AnzTodesfallNeu,AnzFall7T,Inz7T,ObjectId&outSR=4326&f=json")
      return result.data.features
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          outputs: ${{ toJson(on.script.outputs) }}
          FallNeu: ${{ on.script.outputs.atttributes.AnzFallNeu }}
        run: |
          echo outputs: $outputs
          echo Neue Fälle: $FallNeu
