Today maybe raining, temp: ${{on.weather.outputs.current[0].temp}}°, ${{on.weather.outputs.daily[0].weather[0]description}}
on:
  weather:
    apiKey: ${{ secrets.OPENWEATHERMAP_API_KEY }}
    params:
      lat: ${{ secrets.LAT }}
      lon: ${{ secrets.LON }}
      lang: de
      units: metric
    config:
      every: "30 6 * * 1-5"
      timeZone: Europe/Berlin

jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        id: collect_data
        env:
          sunrise: ${{on.weather.outputs.current.sunrise}}
          sunset: ${{on.weather.outputs.current.sunset}}
          #alert_active: ${{on.weather.outputs.alerts[0].description}}
          #alert_start: ${{on.weather.outputs.alerts[0].start}}
          #alert_end: ${{on.weather.outputs.alerts[0].end}}
          message: |
            temp: ${{on.weather.outputs.current.temp}}°, ${{on.weather.outputs.daily[0].weather[0].description}}
        run: |
          echo message: $message
          conv_sunrise=$(date +%H:%M --date='TZ="CET" @'${sunrise})
          conv_sunset=$(date +%H:%M --date='TZ="CET" @'${sunset})
          echo $(date +%Z)
          echo "::set-output name=conv_sunrise::${conv_sunrise}"
          echo "::set-output name=conv_sunset::${conv_sunset}"
     
          #if [${alerts_active} != ""]
          #then
            #conv_alert_start=$(date +%H:%M --date='TZ="CET" @'${alert_start})
            #conv_alert_end=$(date +%H:%M --date='TZ="CET" @'${alert_end})
            #echo "::set-output name=conv_sunrise::${conv_alert_start}"
            #echo "::set-output name=conv_sunset::${conv_alert_end}"
          #fi
      - name: Slack notification daily
        uses: Ilshidur/action-slack@2.1.0
        env:
          curtemp: ${{on.weather.outputs.current.temp}}
          maxtemp: ${{on.weather.outputs.daily[0].temp.day}}
          summary: ${{on.weather.outputs.daily[0].weather[0].description}}
          slacksunrise: "${{steps.collect_data.outputs.conv_sunrise}}"
          slacksunset: "${{steps.collect_data.outputs.conv_sunset}}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEATHER_BOT }}
          #SLACK_CUSTOM_PAYLOAD: '{ "text": "Wetterinfo {{ summary }} ", "blocks": [ { "type": "header", "text": { "type": "plain_text", "text": ":thermometer: Wetterinfo {{ summary }}", "emoji": true } },{ "type": "section", "text": { "type": "mrkdwn", "text": " Aktuelle Temperatur liegt bei {{ curtemp }} °C, die Maximaltemperatur wird bei {{ maxtemp }} °C liegen {{slacksunrise}} {{slacksunset}}" } }, { "type": "divider" } ] }'
        with:
          args: "Wetterinfo:\n
                Aktuelle Temperatur liegt bei {{ curtemp }} °C, die Maximaltemperatur wird bei {{ maxtemp }} °C liegen\n
                Sonnenaufgang: {{ slacksunrise }}\n
                Sonnenuntergang: {{ slacksunset }}\n"
      - name: Slack notification rain
        uses: Ilshidur/action-slack@2.1.0
        if: on.weather.outputs.daily[0].weather[0].main == 'Rain'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEATHER_BOT }}
          SLACK_CUSTOM_PAYLOAD: '{ "text": "Regen ", "blocks": [ { "type": "header", "text": { "type": "plain_text", "text": ":rain_cloud: Wetterinfo ", "emoji": true } },{ "type": "section", "text": { "type": "mrkdwn", "text": "Du solltest den Regenschirm mitnehmen" } }, { "type": "divider" } ] }'
      - name: Slack notification Clouds
        uses: Ilshidur/action-slack@2.1.0
        if: on.weather.outputs.daily[0].weather[0].description == 'Bedeckt'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEATHER_BOT }}
          SLACK_CUSTOM_PAYLOAD: '{ "text": "Wolken ", "blocks": [ { "type": "header", "text": { "type": "plain_text", "text": ":cloud: Wetterinfo ", "emoji": true } },{ "type": "section", "text": { "type": "mrkdwn", "text": "Grau in grau und keine Sonne in Sicht" } }, { "type": "divider" } ] }'
      - name: Slack notification Clouds_behind_sun
        uses: Ilshidur/action-slack@2.1.0
        if: on.weather.outputs.daily[0].weather[0].description == 'Überwiegend bewölkt'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEATHER_BOT }}
          SLACK_CUSTOM_PAYLOAD: '{ "text": "Wolken ", "blocks": [ { "type": "header", "text": { "type": "plain_text", "text": ":sun_behind_cloud: Wetterinfo ", "emoji": true } },{ "type": "section", "text": { "type": "mrkdwn", "text": "Ein kleines bisschen Sonne ist in Sicht" } }, { "type": "divider" } ] }'
      - name: Slack notification alert
        uses: Ilshidur/action-slack@2.1.0
        if: on.weather.outputs.alerts[0].description != ''
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEATHER_BOT }}
          #alert_start: ${{steps.collect_data.outputs.conv_alert_start}}
          #alert_end: ${{steps.collect_data.outputs.conv_alert_end}}
          #alert_desc: ${{on.weather.outputs.alerts[0].description}}
          #SLACK_CUSTOM_PAYLOAD: '{ "text": "Wolken ", "blocks": [ { "type": "header", "text": { "type": "plain_text", "text": ":sun_behind_cloud: Wetterinfo ", "emoji": true } },{ "type": "section", "text": { "type": "mrkdwn", "text": "Ein kleines bisschen Sonne ist in Sicht" } }, { "type": "divider" } ] }'
        with:
          args:
            "ALARM!\n
            {{ alert_desc }}\n
            Gültig von {{ alert_start }} bis {{alert_end }}\n"
          
          
          
