Today maybe raining, temp: ${{on.weather.outputs.current[0].temp}}°, ${{on.weather.outputs.daily[0].weather[0]description}}
on:
  weather:
    apiKey: ${{ secrets.OPENWEATHERMAP_API_KEY }}
    params:
      lat: ${{ secrets.LAT }}
      lon: ${{ secrets.LON }}
      lang: de
      units: metric
    config:
      #every: "30 6 * * 1-5"
      timeZone: Europe/Berlin

jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        continue-on-error: true
        id: collect_data
        env:
          sunrise: ${{on.weather.outputs.current.sunrise}}
          sunset: ${{on.weather.outputs.current.sunset}}
          message: |
            temp: ${{on.weather.outputs.current.temp}}°, ${{on.weather.outputs.daily[0].weather[0].description}}
        run: |
          echo message: $message
          conv_sunrise=$(date +%H:%M --date='TZ="CET" @'${sunrise})
          conv_sunset=$(date +%H:%M --date='TZ="CET" @'${sunset})
          echo $(date +%Z)
          echo "::set-output name=conv_sunrise::${conv_sunrise}"
          echo "::set-output name=conv_sunset::${conv_sunset}"
      - name: send message daily
        uses: appleboy/discord-action@master
        env:
          curtemp: ${{on.weather.outputs.current.temp}}
          maxtemp: ${{on.weather.outputs.daily[0].temp.day}}
          summary: ${{on.weather.outputs.daily[0].weather[0].description}}
          slacksunrise: "${{steps.collect_data.outputs.conv_sunrise}}"
          slacksunset: "${{steps.collect_data.outputs.conv_sunset}}"
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          #color: "#48f442"
          message: "Wetterinfo:\n
                   Aktuelle Temperatur liegt bei {{ curtemp }} °C, die Maximaltemperatur wird bei {{ maxtemp }} °C liegen\n
                   Sonnenaufgang: {{ slacksunrise }}\n
                   Sonnenuntergang: {{ slacksunset }}\n"
                
      - name: Discord notification rain
        uses: appleboy/discord-action@master
        if: on.weather.outputs.daily[0].weather[0].main == 'Rain'
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#ff0000"
          message: ":rain: Du solltest den Regenschirm mitnehmen"
      - name: Discord notification Clouds
        uses: appleboy/discord-action@master
        if: on.weather.outputs.daily[0].weather[0].description == 'Bedeckt'
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#ff0000"
          message: ":cloud: Grau in grau..."        
      - name: Discord notification Clouds_behind_sun
        uses: appleboy/discord-action@master
        if: on.weather.outputs.daily[0].weather[0].description == 'Überwiegend bewölkt'
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#ff0000"
          message: ":sun_behind_cloud: Ein wenig Sonne ist in Sicht"              

