on:
  weather:
    apiKey: ${{ secrets.OPENWEATHERMAP_API_KEY }}
    params:
      lat: ${{ secrets.LAT }}
      lon: ${{ secrets.LON }}
      lang: de
      units: metric
    config:
      every: "0 6-23/3 * * *"
      timeZone: Europe/Berlin

jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        continue-on-error: true
        id: collect_data
        env:
          alert_active: ${{on.weather.outputs.alerts[0].description}}
          alert_start: ${{on.weather.outputs.alerts[0].start}}
          alert_end: ${{on.weather.outputs.alerts[0].end}}
        run: |
          echo Alarmstatus: $alert_active 
          if [ ! -z "${alert_active}" ]
          then
            echo convert dates and export variables
            conv_alert_start=$(date +%H:%M --date='TZ="CET" @'${alert_start})
            conv_alert_end=$(date +%H:%M --date='TZ="CET" @'${alert_end})
            echo "::set-output name=conv_alert_active::${alert_active}"
            echo "::set-output name=conv_alert_start::${conv_alert_start}"
            echo "::set-output name=conv_alert_end::${conv_alert_end}"
          fi
      - name: Discord Alert
        continue-on-error: true
        uses: appleboy/discord-action@master
        if: ${{ on.weather.outputs.alerts[0].description != '' }}
        env:
          alert_start: ${{steps.collect_data.outputs.conv_alert_start}}
          alert_end: ${{steps.collect_data.outputs.conv_alert_end}}
          alert_desc: ${{steps.collect_data.outputs.conv_alert_active}}
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ALERTS_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_ALERTS_TOKEN }}
          message:
            ":bangbang: ALARM :bangbang:\n
            ${{steps.collect_data.outputs.conv_alert_active}}\n
            Gültig von ${{steps.collect_data.outputs.conv_alert_start}} bis ${{steps.collect_data.outputs.conv_alert_end}}\n"
