on:
  webhook:
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          method: ${{ on.webhook.outputs.method }}
          body: ${{ toJson(on.webhook.outputs.body) }}
          headers: ${{ toJson(on.webhook.outputs.headers) }}
        run: |
          wget https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html
          cat Fallzahlen.html
          echo method: $method
          echo headers $headers
          echo body: $body 
      - name: Slack notification
        uses: Ilshidur/action-slack@2.1.0
        if: on.webhook.outputs.body.text == 'blubb'
        env:
          bodytext: ${{ on.webhook.outputs.body.text }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_TEST_CHANNEL }}
          SLACK_CUSTOM_PAYLOAD: '{ "text": "Ya man! {{ bodytext }} "}'
